### ISSUE TITLE
error : bitmap.c -- block corrupt

### ISSUE THREAD

**Issue by Samighz** [sonocotta/esp32-gameboy#2]
Hi
I have this error with esp32 C3 (same for esp32 S3) :
addr: 0x3FCC2204, size: 61440, line 86 of .pio/libdeps/play-esp-a-c3/arduino-nofrendo/src/bitmap.c -- block corrupt

**Comment by anabolyc** [comment]
I have it as well, it comes form the original nofrendo code and doesn't seems to affect anything. At leash I didn't witness any issues despite having this error once in a while. 
@Samighz if you find any more details around this issue I'd be very curious to know more.
